repos:

  # apdev-js hooks
  - repo: local
    hooks:
      - id: check-chars
        name: apdev-js check-chars
        entry: apdev-js check-chars
        language: system
        types_or: [text, ts, javascript]

      - id: check-imports
        name: apdev-js check-imports
        entry: apdev-js check-imports
        language: system
        pass_filenames: false
        always_run: true

  # TypeScript type checking
  - repo: local
    hooks:
      - id: typecheck
        name: tsc --noEmit
        entry: npx tsc --noEmit
        language: system
        pass_filenames: false
        always_run: true
        files: \.(ts|tsx)$
